const socket=io();const code=new URLSearchParams(location.search).get('code');let room,roundIndex=0,current=null,timer=null,soundOn=true;const $=id=>document.getElementById(id);
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let deck=shuffle(QUESTIONS).slice(0,12);if(code){/* compatibility if opened with socket id is not needed */}
socket.emit('teacher:create',{totalRounds:12});
socket.on('teacher:created',async d=>{room=d.room;$('gamecode').textContent=room.code;$('codeText').textContent=room.code;const r=await fetch('/api/join-url');const j=await r.json();$('qr').src=j.qr;$('joinurl').textContent=j.url;});
socket.on('room:update',r=>{room=r;$('count').textContent=r.players.length+'/5';renderPlayers(r.players);$('status').textContent=r.status==='lobby'?'🟢 Lobby':r.status==='question'?'🔵 Question':r.status==='paused'?'⏸️ Paused':r.status==='results'?'🟡 Results':'🏁 Finished';$('start').disabled=r.players.length!==5||r.status!=='lobby';});
function renderPlayers(ps){$('players').innerHTML=ps.map(p=>`<div class="player-card"><div class="cat">🐱</div><b>${esc(p.team)}</b><div class="ready">${p.ready?'● READY':'○ WAITING'}</div><div class="score">${p.score}</div></div>`).join('')}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('start').onclick=()=>{if(room?.players.length===5){startQuestion();socket.emit('teacher:start')}};
$('next').onclick=()=>{startQuestion();socket.emit('teacher:next')};$('pause').onclick=()=>socket.emit('teacher:pause');$('reset').onclick=()=>{if(confirm('Are you sure you want to reset all players and scores?'))socket.emit('teacher:reset')};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'🔊 SOUND':'🔇 SOUND'};
function startQuestion(){current=deck[roundIndex%deck.length];roundIndex++;const opts=shuffle(current.options.map((text,i)=>({text,i})));current._opts=opts;current._correct=opts.findIndex(x=>x.i===current.correctAnswer);$('lobby').classList.add('hidden');$('results').classList.add('hidden');$('final').classList.add('hidden');$('play').classList.remove('hidden');$('round').textContent=`ROUND ${roundIndex}/12`;$('category').textContent=({Common:'💼 COMMON JOBS',Uncommon:'🦄 UNCOMMON JOBS',Creative:'🎨 CREATIVE JOBS',Technical:'💻 TECHNICAL JOBS'})[current.category];$('question').textContent=current.question;opts.forEach((o,i)=>$('door'+i).innerHTML=`${'ABC'[i]}. ${esc(o.text)}`);document.querySelectorAll('.runner').forEach(x=>x.remove());socket.emit('round:setQuestion',{correctIndex:current._correct,question:{question:current.question,options:current._opts.map(o=>o.text),category:current.category}});startTimer(10)}
function startTimer(n){clearInterval(timer);let t=n;$('timer').textContent=t;timer=setInterval(()=>{t--;$('timer').textContent=t;if(t<=0){clearInterval(timer);setTimeout(()=>{if(room?.status==='question')socket.emit('teacher:next')},700)}},1000)}
socket.on('player:move',d=>{let p=room?.players.find(x=>x.id===d.playerId);if(!p)return;const el=document.createElement('div');el.className=`runner to${d.answer}`;el.textContent='🐱';el.title=p.team;$('maze').appendChild(el);if(d.correct){el.classList.add('run');toast('🏆 CORRECT!');}else{toast('❌ WRONG ANSWER');}});
socket.on('round:results',d=>{clearInterval(timer);$('play').classList.add('hidden');$('results').classList.remove('hidden');const by=d.players.sort((a,b)=>b.score-a.score);$('resultList').innerHTML=by.map(p=>`<div class="rank"><b>${p.roundPoints?'⭐ +'+p.roundPoints:'• +0'} ${esc(p.team)}</b><span>${p.score} pts</span></div>`).join('');if(d.rankings.length)toast('🎉 Round complete!')});
socket.on('game:finished',r=>{clearInterval(timer);$('play').classList.add('hidden');$('results').classList.add('hidden');$('final').classList.remove('hidden');const ps=[...(r.players||[])].sort((a,b)=>b.score-a.score);$('finalList').innerHTML=ps.map((p,i)=>`<div class="rank"><b>${['👑','🥈','🥉','🐱','🐱'][i]} ${esc(p.team)}</b><span>${p.score} pts</span></div>`).join('');document.body.insertAdjacentHTML('beforeend','<div class="confetti"></div>');setTimeout(()=>document.querySelector('.confetti')?.remove(),1600)});
socket.on('game:reset',()=>location.reload());socket.on('teacher:error',m=>toast('⚠️ '+m));function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1300)}
