const socket=io();const $=id=>document.getElementById(id);let selectedCat=0,joined=false,current=null,timer=null;const cats=['🐱','🐱','🐱','🐱','🐱'];
$('catPicks').innerHTML=cats.map((c,i)=>`<button class="cat-pick ${i===0?'selected':''}" data-i="${i}">${c}</button>`).join('');document.querySelectorAll('.cat-pick').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat-pick').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedCat=Number(b.dataset.i)});
const q=new URLSearchParams(location.search);if(q.get('code'))$('code').value=q.get('code').toUpperCase();$('join').onclick=()=>{const code=$('code').value.trim().toUpperCase(),team=$('team').value.trim();socket.emit('player:join',{code,team,player:$('player').value.trim(),catId:selectedCat});};
socket.on('connect',()=>{$('conn').textContent='🟢 CONNECTED';$('conn').className='status connected'});socket.on('disconnect',()=>{$('conn').textContent='🔴 CONNECTION LOST';$('conn').className='status disconnected'});socket.on('join:error',m=>$('error').textContent=m);
socket.on('player:joined',d=>{joined=true;$('joinCard').classList.add('hidden');$('wait').classList.remove('hidden');$('myTeam').textContent='🐱 '+d.player.team;$('myCat').textContent='🐱'});
socket.on('round:start',d=>{if(!joined)return;showQuestion(d)});
// The teacher may randomize option order; the phone receives the question from a lightweight room broadcast below.
socket.on('room:update',r=>{if(!joined)return;if(r.status==='finished'){$('phoneQuestion').classList.add('hidden');$('locked').classList.add('hidden');$('phoneFinished').classList.remove('hidden')}});
socket.on('question:send',d=>{if(joined)showQuestion(d)});
function showQuestion(d){let qdata=d.question||QUESTIONS[Math.floor(Math.random()*QUESTIONS.length)];current=qdata;$('locked').classList.add('hidden');$('phoneFinished').classList.add('hidden');$('phoneQuestion').classList.remove('hidden');$('phoneRound').textContent=`ROUND ${d.round||''}`;$('phoneQ').textContent=qdata.question;const opts=qdata.options||[];$('phoneOptions').innerHTML=opts.map((o,i)=>`<button class="option ${['a','b','c'][i]}" data-i="${i}">${'ABC'[i]}. ${o}</button>`).join('');document.querySelectorAll('#phoneOptions .option').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)));let t=10;clearInterval(timer);$('phoneTimer').textContent=t;timer=setInterval(()=>{t--;$('phoneTimer').textContent=t;if(t<=0){clearInterval(timer);lockUI()}},1000)}
function answer(i){if(!current)return;document.querySelectorAll('#phoneOptions .option').forEach(b=>b.disabled=true);socket.emit('player:answer',{answer:i});lockUI()};function lockUI(){$('phoneQuestion').classList.add('hidden');$('locked').classList.remove('hidden')};socket.on('answer:locked',()=>lockUI());
