window.QUESTIONS = [
{question:'Which professional takes care of people’s teeth?',options:['Dentist','Architect','Photographer'],correctAnswer:0,category:'Common'},
{question:'Who prepares and cooks food in a restaurant?',options:['Chef','Cashier','Driver'],correctAnswer:0,category:'Common'},
{question:'Which job usually teaches students in a school?',options:['Teacher','Mechanic','Farmer'],correctAnswer:0,category:'Common'},
{question:'Who designs and builds plans for buildings?',options:['Architect','Nurse','Cashier'],correctAnswer:0,category:'Common'},
{question:'Which professional helps sick or injured people in a hospital?',options:['Doctor','Chef','Accountant'],correctAnswer:0,category:'Common'},
{question:'Who repairs engines and vehicles?',options:['Mechanic','Lawyer','Dentist'],correctAnswer:0,category:'Common'},
{question:'Which job involves protecting people and enforcing laws?',options:['Police Officer','Graphic Designer','Farmer'],correctAnswer:0,category:'Common'},
{question:'Who records and manages financial information for a business?',options:['Accountant','Firefighter','Photographer'],correctAnswer:0,category:'Common'},
{question:'Which worker grows crops and cares for farm animals?',options:['Farmer','Web Developer','Actor'],correctAnswer:0,category:'Common'},
{question:'Who helps put out fires and rescue people?',options:['Firefighter','Fashion Designer','Data Analyst'],correctAnswer:0,category:'Common'},
{question:'Which unusual job involves tasting food made for pets?',options:['Pet Food Taster','Web Developer','Accountant'],correctAnswer:0,category:'Uncommon'},
{question:'A golf ball diver searches for lost balls mainly in what place?',options:['Ponds and lakes','Movie studios','Computer labs'],correctAnswer:0,category:'Uncommon'},
{question:'What does a water slide tester mainly check?',options:['Safety and ride experience','Tax records','Website code'],correctAnswer:0,category:'Uncommon'},
{question:'A snake milker carefully collects what from certain snakes?',options:['Venom','Milk','Fur'],correctAnswer:0,category:'Uncommon'},
{question:'A professional mourner may be hired to do what at a funeral?',options:['Attend and mourn','Design websites','Repair cars'],correctAnswer:0,category:'Uncommon'},
{question:'What might an odor tester evaluate?',options:['How something smells','How fast a computer is','How tall a building is'],correctAnswer:0,category:'Uncommon'},
{question:'A fortune cookie writer creates what?',options:['Short messages or predictions','Computer networks','Dental tools'],correctAnswer:0,category:'Uncommon'},
{question:'A line stand-in is paid to do what?',options:['Wait in a queue for someone','Train athletes','Edit films'],correctAnswer:0,category:'Uncommon'},
{question:'A professional sleeper may be hired to test what?',options:['Beds or sleep products','Bridges','Cooking recipes'],correctAnswer:0,category:'Uncommon'},
{question:'A water slide tester should pay special attention to what?',options:['Safety','Accounting','Typography'],correctAnswer:0,category:'Uncommon'},
{question:'Which creative professional creates visual designs for ads and social media?',options:['Graphic Designer','Accountant','Security Guard'],correctAnswer:0,category:'Creative'},
{question:'Who creates moving visual images for films, games, or media?',options:['Animator','Dentist','Farmer'],correctAnswer:0,category:'Creative'},
{question:'Which job focuses on taking and composing photographs?',options:['Photographer','Network Engineer','Chef'],correctAnswer:0,category:'Creative'},
{question:'Who creates clothing styles and fashion collections?',options:['Fashion Designer','Police Officer','Data Analyst'],correctAnswer:0,category:'Creative'},
{question:'Which creative job creates drawings and visual artwork for books or media?',options:['Illustrator','Mechanic','Cloud Engineer'],correctAnswer:0,category:'Creative'},
{question:'Who creates and arranges recorded music?',options:['Music Producer','Lawyer','Nurse'],correctAnswer:0,category:'Creative'},
{question:'Which job involves performing characters for movies or theater?',options:['Actor','Accountant','Cybersecurity Specialist'],correctAnswer:0,category:'Creative'},
{question:'Who plans and leads the creative vision of a film?',options:['Film Director','Farmer','IT Support Specialist'],correctAnswer:0,category:'Creative'},
{question:'Which professional plans the look and function of indoor spaces?',options:['Interior Designer','Firefighter','Database Administrator'],correctAnswer:0,category:'Creative'},
{question:'Who designs the visual experience of a video game?',options:['Game Designer','Dentist','Cashier'],correctAnswer:0,category:'Creative'},
{question:'Which technology professional writes code to build software?',options:['Software Developer','Fashion Designer','Chef'],correctAnswer:0,category:'Technical'},
{question:'Who creates and maintains websites?',options:['Web Developer','Farmer','Actor'],correctAnswer:0,category:'Technical'},
{question:'Which job studies data to find useful patterns and insights?',options:['Data Analyst','Firefighter','Photographer'],correctAnswer:0,category:'Technical'},
{question:'Who helps protect computer systems from digital attacks?',options:['Cybersecurity Specialist','Fashion Designer','Driver'],correctAnswer:0,category:'Technical'},
{question:'Which professional designs and manages computer networks?',options:['Network Engineer','Graphic Designer','Chef'],correctAnswer:0,category:'Technical'},
{question:'Who develops systems that use artificial intelligence?',options:['AI Engineer','Accountant','Actor'],correctAnswer:0,category:'Technical'},
{question:'Which job designs or builds machines that can perform tasks automatically?',options:['Robotics Engineer','Teacher','Lawyer'],correctAnswer:0,category:'Technical'},
{question:'Who designs digital interfaces to make apps easier to use?',options:['UX/UI Designer','Mechanic','Dentist'],correctAnswer:0,category:'Technical'},
{question:'Which specialist manages organized collections of digital information?',options:['Database Administrator','Photographer','Farmer'],correctAnswer:0,category:'Technical'},
{question:'Who helps maintain computing services delivered over the internet?',options:['Cloud Engineer','Chef','Police Officer'],correctAnswer:0,category:'Technical'}
];
